name: TeisyokuPlugin2
version: 2.4.0
main: net.jp.minecraft.plugins.TeisyokuPlugin2
commands:
    help:
        description: Teisyoku Help Command
        usage: /help
    fly:
        description: Teisyoku Fly Command
        usage: /fly (true/false)
    gomi:
        description: Gomibako.
        usage: /gomi
    gomibako:
        description: Gomibako.
        usage: /gomi
    teisyoku:
        description: teisyoku.
        usage: /teisyoku
    t:
        description: teisyoku.
        usage: /t
    players:
        description: show players list.
        usage: /players
    p:
        description: show players list.
        usage: /p
    last:
        description: show player last login date.
        usage: /last <Player>
    ad:
        description: Teisyoku Ad.
        usage: /ad <Messages>
    notice:
        description: Teisyoku Ad.
        usage: /notice <Messages>
    call:
        description: Teisyoku Call.
        usage: /call <Player> <Messages>
    cart:
        description: Give to Minecart.
        usage: /cart
    minecart:
        description: Give to Minecart.
        usage: /minecart
    nick:
        description: Nick
        usage: /nick
    nickname:
        description: Nickname
        usage: /nickname
    point:
        description: TPoint
        usage: /point
    tpoint:
        description: TPoint
        usage: /tpoint
    tt:
        description: TPoint
        usage: /tpoint
    ri:
        description: RailwayInfo
        usage: /ri
    railwayinfo:
        description: RailwayInfo
        usage: /railwayinfo
permissions:
    teisyoku.*:
        description: Allow using TeisyokuPlugin2.
        default: op
    teisyoku.user:
        description: Teisyoku.
        default: op
    teisyoku.admin:
        description: Teisyoku.
        default: op
